name: Deploy Hugo site to GitHub Pages (gh-pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: hugo-pages
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (for PostCSS/Tailwind if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm ci --no-audit --no-fund
          fi

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          commit_message: "Deploy: ${{ github.sha }}"
          force_orphan: true

